# Generated by Django 4.1.4 on 2023-01-27 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=15)),
                ('organ_pledged', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
