# Generated by Django 4.1.4 on 2023-01-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_person_date_remove_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='des1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='des2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='des3',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
