# Generated by Django 4.1.4 on 2023-01-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_person_des1_alter_person_des2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='selfdesc',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
