# Generated by Django 4.1.7 on 2023-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_person_selfdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrs', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='des1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='person',
            name='des2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='person',
            name='des3',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
